export type FieldType =
  | "text"
  | "number"
  | "money"
  | "date"
  | "datetime"
  | "textarea"
  | "select"
  | "ref"
  | "boolean";

export interface FieldDef {
  name: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: string[];
  ref?: { table: string; label: string };
  help?: string;
  filter?: { column: string; value: string };
}

export interface EntityDef {
  key: string;
  table: string;
  label: string;
  singular: string;
  modulo: string;
  descricao: string;
  fields: FieldDef[];
  list: string[];
  order?: { column: string; asc?: boolean };
  fixed?: Record<string, string>;
  financeiro?: boolean;
}

const obs: FieldDef = { name: "observacoes", label: "Observações", type: "textarea" };
const unidades = ["kg", "saco", "litro", "dose", "unidade", "tonelada", "ha", "l/ha"];

const talhaoRef: FieldDef = {
  name: "talhao_id",
  label: "Talhão",
  type: "ref",
  ref: { table: "talhoes", label: "nome" },
  required: true,
};
const produtoRef: FieldDef = {
  name: "produto_id",
  label: "Produto / insumo",
  type: "ref",
  ref: { table: "produtos", label: "nome" },
  required: true,
};

export const MODULOS: { key: string; label: string }[] = [
  { key: "cadastros", label: "Cadastros" },
  { key: "lavoura", label: "Lavoura" },
  { key: "comercial", label: "Contratos e Romaneios" },
  { key: "pecuaria", label: "Pecuária e Ovinos" },
  { key: "aves", label: "Aves e Galinheiro" },
  { key: "piscicultura", label: "Piscicultura" },
  { key: "estoque", label: "Estoque" },
  { key: "financeiro", label: "Financeiro" },
  { key: "rh", label: "Pessoal" },
];

export const ENTITIES: EntityDef[] = [
  // ============ CADASTROS ============
  {
    key: "talhoes",
    table: "talhoes",
    label: "Talhões",
    singular: "Talhão",
    modulo: "cadastros",
    descricao: "Áreas de plantio da fazenda",
    fields: [
      { name: "nome", label: "Nome / número", type: "text", required: true },
      { name: "area_ha", label: "Área (ha)", type: "number", required: true },
      { name: "cultura_atual", label: "Cultura atual", type: "text" },
      { name: "safra", label: "Safra", type: "text", help: "Ex.: 2025/2026" },
      obs,
    ],
    list: ["nome", "area_ha", "cultura_atual", "safra"],
    order: { column: "nome", asc: true },
  },
  {
    key: "culturas",
    table: "culturas",
    label: "Culturas",
    singular: "Cultura",
    modulo: "cadastros",
    descricao: "Soja, milho, hortaliças, pastagem e outras",
    fields: [
      { name: "nome", label: "Nome", type: "text", required: true },
      { name: "ciclo", label: "Ciclo", type: "text" },
      obs,
    ],
    list: ["nome", "ciclo"],
    order: { column: "nome", asc: true },
  },
  {
    key: "produtos",
    table: "produtos",
    label: "Produtos e insumos",
    singular: "Produto",
    modulo: "cadastros",
    descricao: "Sementes, adubos, defensivos, rações, sal, medicamentos e alimentos",
    fields: [
      { name: "nome", label: "Nome", type: "text", required: true },
      {
        name: "categoria",
        label: "Categoria",
        type: "select",
        required: true,
        options: [
          "semente",
          "adubo",
          "defensivo",
          "racao",
          "sal",
          "medicamento",
          "alimento",
          "combustivel",
          "peca",
          "outro",
        ],
      },
      { name: "unidade", label: "Unidade", type: "select", required: true, options: unidades },
      { name: "estoque_minimo", label: "Estoque mínimo", type: "number" },
      obs,
    ],
    list: ["nome", "categoria", "unidade", "estoque_minimo"],
    order: { column: "nome", asc: true },
  },
  {
    key: "parceiros",
    table: "parceiros",
    label: "Clientes e fornecedores",
    singular: "Parceiro",
    modulo: "cadastros",
    descricao: "Compradores de grãos e animais, fornecedores de insumos",
    fields: [
      { name: "nome", label: "Nome / razão social", type: "text", required: true },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        required: true,
        options: ["cliente", "fornecedor", "ambos"],
      },
      { name: "documento", label: "CNPJ / CPF", type: "text" },
      { name: "contato", label: "Contato", type: "text" },
      { name: "endereco", label: "Endereço", type: "textarea" },
    ],
    list: ["nome", "tipo", "documento", "contato"],
    order: { column: "nome", asc: true },
  },
  {
    key: "armazens",
    table: "armazens",
    label: "Armazéns",
    singular: "Armazém",
    modulo: "cadastros",
    descricao: "Destinos de entrega dos contratos",
    fields: [
      { name: "nome", label: "Nome", type: "text", required: true },
      { name: "localizacao", label: "Localização", type: "text" },
    ],
    list: ["nome", "localizacao"],
    order: { column: "nome", asc: true },
  },
  {
    key: "maquinas",
    table: "maquinas",
    label: "Parque de máquinas",
    singular: "Máquina",
    modulo: "cadastros",
    descricao: "Colheitadeiras, plantadeiras, plataformas, caminhões, motos e pulverizadores",
    fields: [
      { name: "nome", label: "Identificação", type: "text", required: true },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          "colheitadeira",
          "plantadeira",
          "plataforma_milho",
          "plataforma_soja",
          "caminhao",
          "caminhonete",
          "moto",
          "pulverizador",
          "tratador",
          "outro",
        ],
      },
      { name: "marca", label: "Marca", type: "text" },
      { name: "modelo", label: "Modelo", type: "text" },
      { name: "ano", label: "Ano", type: "number" },
      { name: "placa", label: "Placa", type: "text" },
      obs,
    ],
    list: ["nome", "tipo", "marca", "modelo", "ano", "placa"],
    order: { column: "nome", asc: true },
  },
  {
    key: "pastos",
    table: "pastos",
    label: "Pastos e piquetes",
    singular: "Pasto",
    modulo: "cadastros",
    descricao: "Áreas de pastagem do rebanho",
    fields: [
      { name: "nome", label: "Nome", type: "text", required: true },
      { name: "area_ha", label: "Área (ha)", type: "number" },
      { name: "capacidade", label: "Capacidade (cabeças)", type: "number" },
      obs,
    ],
    list: ["nome", "area_ha", "capacidade"],
    order: { column: "nome", asc: true },
  },
  {
    key: "tanques",
    table: "tanques",
    label: "Tanques e viveiros",
    singular: "Tanque",
    modulo: "cadastros",
    descricao: "Estruturas da piscicultura",
    fields: [
      { name: "nome", label: "Nome", type: "text", required: true },
      { name: "especie", label: "Espécie", type: "text" },
      { name: "capacidade", label: "Capacidade", type: "number" },
      obs,
    ],
    list: ["nome", "especie", "capacidade"],
    order: { column: "nome", asc: true },
  },

  // ============ LAVOURA ============
  {
    key: "plantios",
    table: "plantios",
    label: "Plantios",
    singular: "Plantio",
    modulo: "lavoura",
    descricao: "Semeadura por talhão e safra",
    fields: [
      talhaoRef,
      { name: "cultura", label: "Cultura", type: "text", required: true },
      { name: "variedade", label: "Variedade / semente", type: "text" },
      { name: "data_plantio", label: "Data do plantio", type: "date", required: true },
      { name: "quantidade_semente", label: "Quantidade de semente", type: "number" },
      { name: "unidade", label: "Unidade", type: "select", options: unidades },
      { name: "safra", label: "Safra", type: "text" },
      obs,
    ],
    list: ["data_plantio", "talhao_id", "cultura", "variedade", "safra"],
    order: { column: "data_plantio" },
  },
  {
    key: "analises_solo",
    table: "analises_solo",
    label: "Análises de solo",
    singular: "Análise de solo",
    modulo: "lavoura",
    descricao: "Laudos por talhão, com anexo do PDF",
    fields: [
      talhaoRef,
      { name: "data", label: "Data", type: "date", required: true },
      { name: "laboratorio", label: "Laboratório", type: "text" },
      { name: "resultado", label: "Resultado do laudo", type: "textarea" },
      obs,
    ],
    list: ["data", "talhao_id", "laboratorio"],
    order: { column: "data" },
  },
  {
    key: "adubacoes",
    table: "adubacoes",
    label: "Adubações",
    singular: "Adubação",
    modulo: "lavoura",
    descricao: "Aplicação de adubo por talhão",
    fields: [
      talhaoRef,
      produtoRef,
      { name: "quantidade", label: "Quantidade", type: "number", required: true },
      { name: "unidade", label: "Unidade", type: "select", options: unidades },
      { name: "data", label: "Data", type: "date", required: true },
      {
        name: "forma_aplicacao",
        label: "Forma de aplicação",
        type: "select",
        options: ["a lanço", "incorporado", "no sulco", "foliar", "fertirrigação"],
      },
      obs,
    ],
    list: ["data", "talhao_id", "produto_id", "quantidade", "forma_aplicacao"],
    order: { column: "data" },
  },
  {
    key: "aplicacoes_defensivos",
    table: "aplicacoes_defensivos",
    label: "Defensivos",
    singular: "Aplicação de defensivo",
    modulo: "lavoura",
    descricao: "Herbicidas, fungicidas e inseticidas aplicados",
    fields: [
      talhaoRef,
      produtoRef,
      { name: "dose", label: "Dose", type: "number", required: true },
      { name: "unidade", label: "Unidade", type: "select", options: unidades },
      { name: "data", label: "Data", type: "date", required: true },
      {
        name: "tipo_alvo",
        label: "Tipo de alvo",
        type: "select",
        options: ["praga", "doenca", "planta_daninha", "outro"],
      },
      { name: "alvo", label: "Alvo", type: "text" },
      obs,
    ],
    list: ["data", "talhao_id", "produto_id", "dose", "tipo_alvo", "alvo"],
    order: { column: "data" },
  },
  {
    key: "ocorrencias_lavoura",
    table: "ocorrencias_lavoura",
    label: "Ocorrências",
    singular: "Ocorrência",
    modulo: "lavoura",
    descricao: "Problemas no desenvolvimento da lavoura",
    fields: [
      talhaoRef,
      { name: "data", label: "Data", type: "date", required: true },
      {
        name: "tipo",
        label: "Tipo de problema",
        type: "select",
        required: true,
        options: [
          "praga",
          "doenca",
          "estresse_hidrico",
          "acamamento",
          "deficiencia_nutricional",
          "granizo",
          "geada",
          "outro",
        ],
      },
      { name: "severidade", label: "Severidade", type: "select", options: ["baixa", "media", "alta"] },
      { name: "descricao", label: "Descrição", type: "textarea" },
      { name: "acao_tomada", label: "Ação tomada", type: "textarea" },
      { name: "safra", label: "Safra", type: "text" },
    ],
    list: ["data", "talhao_id", "tipo", "severidade"],
    order: { column: "data" },
  },

  // ============ COMERCIAL ============
  {
    key: "contratos",
    table: "contratos",
    label: "Contratos",
    singular: "Contrato",
    modulo: "comercial",
    descricao: "Compra e venda de soja e milho, com % de entrega automático",
    fields: [
      { name: "numero", label: "Número do contrato", type: "text" },
      { name: "tipo", label: "Tipo", type: "select", required: true, options: ["venda", "compra"] },
      {
        name: "parceiro_id",
        label: "Cliente / fornecedor",
        type: "ref",
        ref: { table: "parceiros", label: "nome" },
        required: true,
      },
      {
        name: "armazem_id",
        label: "Armazém de destino",
        type: "ref",
        ref: { table: "armazens", label: "nome" },
      },
      { name: "cultura", label: "Cultura", type: "select", required: true, options: ["soja", "milho", "outra"] },
      { name: "quantidade_kg", label: "Quantidade contratada (kg)", type: "number", required: true },
      { name: "preco", label: "Preço (por saca ou kg)", type: "money" },
      { name: "data_contrato", label: "Data da venda/compra", type: "date" },
      { name: "data_inicio_entrega", label: "Início da entrega", type: "date" },
      { name: "data_conclusao_prevista", label: "Conclusão prevista", type: "date" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["em_andamento", "concluido", "cancelado"],
      },
      obs,
    ],
    list: ["numero", "tipo", "parceiro_id", "cultura", "quantidade_kg", "percentual_entrega", "status"],
    order: { column: "data_contrato" },
  },
  {
    key: "romaneios",
    table: "romaneios",
    label: "Romaneios",
    singular: "Romaneio",
    modulo: "comercial",
    descricao: "Cargas e descargas; o peso líquido e a entrega do contrato são calculados sozinhos",
    fields: [
      { name: "numero", label: "Número do romaneio", type: "text", required: true },
      { name: "data_hora", label: "Data e hora", type: "datetime", required: true },
      talhaoRef,
      {
        name: "contrato_id",
        label: "Contrato de venda",
        type: "ref",
        ref: { table: "contratos", label: "numero" },
      },
      {
        name: "armazem_id",
        label: "Armazém",
        type: "ref",
        ref: { table: "armazens", label: "nome" },
      },
      { name: "cultura", label: "Cultura", type: "select", options: ["soja", "milho", "outra"] },
      { name: "placa", label: "Placa do caminhão", type: "text" },
      { name: "motorista", label: "Motorista", type: "text" },
      { name: "peso_bruto", label: "Peso bruto (kg)", type: "number", required: true },
      { name: "peso_tara", label: "Peso tara (kg)", type: "number", required: true },
      { name: "origem", label: "Origem", type: "select", options: ["colheita", "silo_bag"] },
      { name: "nota_fiscal", label: "Nota fiscal", type: "text" },
      { name: "impureza", label: "Impureza (%)", type: "number" },
      { name: "umidade", label: "Umidade (%)", type: "number" },
      { name: "avariados", label: "Avariados (%)", type: "number" },
      { name: "mofado", label: "Mofado (%)", type: "number" },
      { name: "verde", label: "Verde (%)", type: "number" },
      { name: "quebrados", label: "Quebrados (%)", type: "number" },
      { name: "outros", label: "Outras observações da classificação", type: "textarea" },
    ],
    list: ["numero", "data_hora", "talhao_id", "contrato_id", "placa", "peso_liquido", "origem"],
    order: { column: "data_hora" },
  },

  // ============ PECUARIA ============
  {
    key: "bovinos",
    table: "animais",
    label: "Rebanho bovino",
    singular: "Bovino",
    modulo: "pecuaria",
    descricao: "Cabeças de gado de corte",
    fixed: { especie: "bovino" },
    fields: [
      { name: "identificacao", label: "Brinco / identificação", type: "text", required: true },
      { name: "nome", label: "Nome", type: "text" },
      { name: "sexo", label: "Sexo", type: "select", options: ["macho", "femea"] },
      { name: "raca", label: "Raça", type: "text" },
      { name: "data_nascimento", label: "Data de nascimento", type: "date" },
      { name: "peso", label: "Peso (kg)", type: "number" },
      { name: "pasto_id", label: "Pasto atual", type: "ref", ref: { table: "pastos", label: "nome" } },
      { name: "lote", label: "Lote", type: "text" },
      { name: "status", label: "Situação", type: "select", options: ["ativo", "vendido", "abatido", "morto"] },
      obs,
    ],
    list: ["identificacao", "sexo", "raca", "data_nascimento", "pasto_id", "lote", "status"],
    order: { column: "identificacao", asc: true },
  },
  {
    key: "ovinos",
    table: "animais",
    label: "Rebanho ovino",
    singular: "Ovino",
    modulo: "pecuaria",
    descricao: "Carneiros e ovelhas",
    fixed: { especie: "ovino" },
    fields: [
      { name: "identificacao", label: "Brinco / identificação", type: "text", required: true },
      { name: "sexo", label: "Sexo", type: "select", options: ["macho", "femea"] },
      { name: "raca", label: "Raça", type: "text" },
      { name: "data_nascimento", label: "Data de nascimento", type: "date" },
      { name: "peso", label: "Peso (kg)", type: "number" },
      { name: "pasto_id", label: "Pasto atual", type: "ref", ref: { table: "pastos", label: "nome" } },
      { name: "lote", label: "Lote", type: "text" },
      { name: "status", label: "Situação", type: "select", options: ["ativo", "vendido", "abatido", "morto"] },
      obs,
    ],
    list: ["identificacao", "sexo", "raca", "data_nascimento", "pasto_id", "status"],
    order: { column: "identificacao", asc: true },
  },
  {
    key: "vacinacoes",
    table: "vacinacoes",
    label: "Vacinas",
    singular: "Vacinação",
    modulo: "pecuaria",
    descricao: "Vacinas aplicadas em animais ou lotes",
    fields: [
      { name: "especie", label: "Espécie", type: "select", required: true, options: ["bovino", "ovino"] },
      { name: "vacina", label: "Vacina", type: "text", required: true },
      { name: "data", label: "Data", type: "date", required: true },
      {
        name: "animal_id",
        label: "Animal (opcional)",
        type: "ref",
        ref: { table: "animais", label: "identificacao" },
      },
      { name: "lote", label: "Lote vacinado", type: "text" },
      { name: "lote_vacina", label: "Lote da vacina", type: "text" },
      { name: "dose", label: "Dose", type: "text" },
      { name: "proximo_reforco", label: "Próximo reforço", type: "date" },
    ],
    list: ["data", "especie", "vacina", "animal_id", "lote", "proximo_reforco"],
    order: { column: "data" },
  },
  {
    key: "nascimentos",
    table: "nascimentos",
    label: "Nascimentos",
    singular: "Nascimento",
    modulo: "pecuaria",
    descricao: "Bezerros, novilhas e cordeiros",
    fields: [
      { name: "especie", label: "Espécie", type: "select", required: true, options: ["bovino", "ovino"] },
      { name: "data", label: "Data", type: "date", required: true },
      { name: "identificacao", label: "Brinco do filhote", type: "text" },
      { name: "mae_id", label: "Mãe", type: "ref", ref: { table: "animais", label: "identificacao" } },
      { name: "sexo", label: "Sexo", type: "select", options: ["macho", "femea"] },
      { name: "peso", label: "Peso (kg)", type: "number" },
      obs,
    ],
    list: ["data", "especie", "identificacao", "mae_id", "sexo", "peso"],
    order: { column: "data" },
  },
  {
    key: "vendas_animais",
    table: "vendas_animais",
    label: "Vendas de animais",
    singular: "Venda de animais",
    modulo: "pecuaria",
    descricao: "Vendas com número da GTA e anexo do documento",
    fields: [
      { name: "especie", label: "Espécie", type: "select", required: true, options: ["bovino", "ovino"] },
      {
        name: "parceiro_id",
        label: "Comprador",
        type: "ref",
        ref: { table: "parceiros", label: "nome" },
        required: true,
      },
      { name: "data", label: "Data", type: "date", required: true },
      { name: "quantidade", label: "Quantidade", type: "number", required: true },
      { name: "valor", label: "Valor total", type: "money" },
      { name: "gta", label: "Número da GTA", type: "text" },
      obs,
    ],
    list: ["data", "especie", "parceiro_id", "quantidade", "valor", "gta"],
    order: { column: "data" },
  },
  {
    key: "abates",
    table: "abates",
    label: "Abates para consumo",
    singular: "Abate",
    modulo: "pecuaria",
    descricao: "Abates de bovinos, ovinos, aves e peixes",
    fields: [
      {
        name: "especie",
        label: "Espécie",
        type: "select",
        required: true,
        options: ["bovino", "ovino", "ave", "peixe"],
      },
      { name: "data", label: "Data", type: "date", required: true },
      { name: "quantidade", label: "Quantidade", type: "number", required: true },
      { name: "peso", label: "Peso total (kg)", type: "number" },
      { name: "finalidade", label: "Finalidade", type: "select", options: ["consumo", "refeitorio", "venda"] },
      obs,
    ],
    list: ["data", "especie", "quantidade", "peso", "finalidade"],
    order: { column: "data" },
  },

  // ============ AVES ============
  {
    key: "lotes_aves",
    table: "lotes_aves",
    label: "Lotes de aves",
    singular: "Lote de aves",
    modulo: "aves",
    descricao: "Galinheiros e lotes de poedeiras",
    fields: [
      { name: "nome", label: "Nome do lote", type: "text", required: true },
      { name: "raca", label: "Raça", type: "text" },
      { name: "quantidade", label: "Quantidade de aves", type: "number", required: true },
      { name: "data_entrada", label: "Data de entrada", type: "date" },
      { name: "galinheiro", label: "Galinheiro", type: "text" },
      obs,
    ],
    list: ["nome", "raca", "quantidade", "data_entrada", "galinheiro"],
    order: { column: "data_entrada" },
  },
  {
    key: "producao_ovos",
    table: "producao_ovos",
    label: "Produção de ovos",
    singular: "Produção de ovos",
    modulo: "aves",
    descricao: "Recolhimento diário por lote",
    fields: [
      { name: "data", label: "Data", type: "date", required: true },
      {
        name: "lote_id",
        label: "Lote / galinheiro",
        type: "ref",
        ref: { table: "lotes_aves", label: "nome" },
      },
      { name: "quantidade", label: "Ovos recolhidos", type: "number", required: true },
      obs,
    ],
    list: ["data", "lote_id", "quantidade"],
    order: { column: "data" },
  },

  // ============ PISCICULTURA ============
  {
    key: "povoamentos",
    table: "povoamentos",
    label: "Povoamentos",
    singular: "Povoamento",
    modulo: "piscicultura",
    descricao: "Entrada de alevinos nos tanques",
    fields: [
      {
        name: "tanque_id",
        label: "Tanque",
        type: "ref",
        ref: { table: "tanques", label: "nome" },
        required: true,
      },
      { name: "data", label: "Data", type: "date", required: true },
      { name: "especie", label: "Espécie", type: "text" },
      { name: "quantidade_alevinos", label: "Quantidade de alevinos", type: "number", required: true },
      obs,
    ],
    list: ["data", "tanque_id", "especie", "quantidade_alevinos"],
    order: { column: "data" },
  },
  {
    key: "despescas",
    table: "despescas",
    label: "Despescas",
    singular: "Despesca",
    modulo: "piscicultura",
    descricao: "Retirada de peixes para venda ou consumo",
    fields: [
      {
        name: "tanque_id",
        label: "Tanque",
        type: "ref",
        ref: { table: "tanques", label: "nome" },
        required: true,
      },
      { name: "data", label: "Data", type: "date", required: true },
      { name: "quantidade", label: "Quantidade de peixes", type: "number" },
      { name: "peso_kg", label: "Peso total (kg)", type: "number" },
      { name: "destino", label: "Destino", type: "select", options: ["venda", "consumo", "refeitorio"] },
      obs,
    ],
    list: ["data", "tanque_id", "quantidade", "peso_kg", "destino"],
    order: { column: "data" },
  },

  // ============ ESTOQUE ============
  {
    key: "estoque_movimentos",
    table: "estoque_movimentos",
    label: "Movimentações de estoque",
    singular: "Movimentação",
    modulo: "estoque",
    descricao: "Entradas, saídas por área e ajustes",
    fields: [
      produtoRef,
      { name: "tipo", label: "Tipo", type: "select", required: true, options: ["entrada", "saida", "ajuste"] },
      { name: "quantidade", label: "Quantidade", type: "number", required: true },
      { name: "data", label: "Data", type: "date", required: true },
      {
        name: "area",
        label: "Área de destino",
        type: "select",
        options: [
          "refeitorio",
          "lavoura",
          "pecuaria",
          "ovinos",
          "aves",
          "piscicultura",
          "maquinas",
          "dormitorio",
          "nota_fiscal",
          "outra",
        ],
      },
      { name: "referencia", label: "Referência (talhão, pasto, lote)", type: "text" },
      { name: "responsavel", label: "Responsável", type: "text" },
      obs,
    ],
    list: ["data", "produto_id", "tipo", "quantidade", "area", "referencia", "responsavel"],
    order: { column: "data" },
  },

  // ============ FINANCEIRO ============
  // Notas fiscais têm tela própria (master-detail) em /notas-fiscais.

  {
    key: "contas",
    table: "contas",
    label: "Contas a pagar e receber",
    singular: "Conta",
    modulo: "financeiro",
    descricao: "Vencimentos, pagamentos e recebimentos",
    financeiro: true,
    fields: [
      { name: "tipo", label: "Tipo", type: "select", required: true, options: ["pagar", "receber"] },
      { name: "descricao", label: "Descrição", type: "text", required: true },
      {
        name: "categoria",
        label: "Categoria",
        type: "select",
        options: [
          "insumos",
          "combustivel",
          "manutencao",
          "folha",
          "impostos",
          "frete",
          "alimentacao",
          "grãos",
          "animais",
          "outra",
        ],
      },
      {
        name: "parceiro_id",
        label: "Cliente / fornecedor",
        type: "ref",
        ref: { table: "parceiros", label: "nome" },
      },
      { name: "valor", label: "Valor", type: "money", required: true },
      { name: "vencimento", label: "Vencimento", type: "date", required: true },
      { name: "status", label: "Status", type: "select", required: true, options: ["pendente", "pago"] },
      {
        name: "forma_pagamento",
        label: "Forma de pagamento",
        type: "select",
        options: ["pix", "dinheiro", "boleto", "transferencia", "cartao", "cheque", "permuta"],
      },
      { name: "data_pagamento", label: "Data do pagamento", type: "date" },
      obs,
    ],
    list: ["vencimento", "tipo", "descricao", "categoria", "valor", "status"],
    order: { column: "vencimento" },
  },

  // ============ RH ============
  {
    key: "funcionarios",
    table: "funcionarios",
    label: "Funcionários",
    singular: "Funcionário",
    modulo: "rh",
    descricao: "Cadastro completo da equipe",
    financeiro: true,
    fields: [
      { name: "nome", label: "Nome", type: "text", required: true },
      { name: "cpf", label: "CPF", type: "text" },
      { name: "cargo", label: "Cargo", type: "text" },
      { name: "funcao", label: "Função", type: "text" },
      { name: "salario", label: "Salário", type: "money" },
      { name: "data_admissao", label: "Data de admissão", type: "date" },
      { name: "banco", label: "Banco", type: "text" },
      { name: "agencia", label: "Agência", type: "text" },
      { name: "conta", label: "Conta", type: "text" },
      { name: "pix", label: "Chave PIX", type: "text" },
      { name: "ativo", label: "Ativo", type: "boolean" },
    ],
    list: ["nome", "cargo", "funcao", "salario", "data_admissao", "ativo"],
    order: { column: "nome", asc: true },
  },
  {
    key: "folha_pagamento",
    table: "folha_pagamento",
    label: "Folha de pagamento",
    singular: "Folha",
    modulo: "rh",
    descricao: "Histórico mensal por funcionário",
    financeiro: true,
    fields: [
      {
        name: "funcionario_id",
        label: "Funcionário",
        type: "ref",
        ref: { table: "funcionarios", label: "nome" },
        required: true,
      },
      { name: "mes", label: "Mês", type: "number", required: true },
      { name: "ano", label: "Ano", type: "number", required: true },
      { name: "salario_base", label: "Salário base", type: "money", required: true },
      { name: "adicionais", label: "Adicionais", type: "money" },
      { name: "descontos", label: "Descontos", type: "money" },
      { name: "status", label: "Status", type: "select", required: true, options: ["pendente", "pago"] },
      { name: "data_pagamento", label: "Data do pagamento", type: "date" },
      obs,
    ],
    list: ["ano", "mes", "funcionario_id", "salario_base", "adicionais", "descontos", "valor_liquido", "status"],
    order: { column: "ano" },
  },
];

export function getEntity(key: string): EntityDef | undefined {
  return ENTITIES.find((e) => e.key === key);
}

export const FIELD_LABELS: Record<string, string> = {
  percentual_entrega: "% entregue",
  peso_liquido: "Peso líquido (kg)",
  valor_liquido: "Valor líquido",
};

export function labelFor(entity: EntityDef, column: string): string {
  const field = entity.fields.find((f) => f.name === column);
  return field?.label ?? FIELD_LABELS[column] ?? column.replace(/_/g, " ");
}
