revoke execute on function public.saldo_produto(uuid) from anon, authenticated;
revoke execute on function public.estoque_custo() from anon, authenticated;
revoke execute on function public.nf_bloqueia_exclusao() from anon, authenticated;
revoke execute on function public.nf_item_estoque() from anon, authenticated;
revoke execute on function public.touch_updated_at() from anon, authenticated;
revoke execute on function public.recalc_contrato_entrega() from anon, authenticated;
revoke execute on function public.handle_new_user() from anon, authenticated;
revoke execute on function public.has_role(uuid, public.app_role) from anon;
revoke execute on function public.is_gestor() from anon;
revoke execute on function public.can_operate() from anon;
revoke execute on function public.can_finance() from anon;